"""Primera Migracion

Revision ID: 1bd53d928978
Revises: 
Create Date: 2026-02-25 20:19:58.095854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bd53d928978'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=50), nullable=True))
        batch_op.alter_column('apaterno',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=0),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.alter_column('apaterno',
               existing_type=sa.String(length=0),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
